### ISSUE TITLE
[task] tracking success of `npe2 fetch`

### ISSUE THREAD

**Issue by tlambert03** [napari/npe2#190]
#185  added the `npe2 fetch` command.  The goal is to be able fetch the manifest for any plugin, npe2 or npe1, from remote sources.

This issue is just to track some of the remaining failures we're seeing.  Checked items mean action has been taken to fix (either by us or the dev)

## Package needs to fix manifest

- [x] `napari-flowering-apple-tree-pixel-classification` - not a valid display_name.
   - display name was too long: #191
   - appears to be fixed in https://github.com/hereariim/napari-flowering-apple-tree-pixel-classification/commit/fa1221f427ccb1d5c942eafc875a7ccbee45a402
   - awaiting new release

## Package needs to update dependencies or build

- [x] `napari-IP-workflow` - has `skimage` in their dependencies (fix submitted https://github.com/jayunruh/napari-ip-workflow/pull/1)
- [ ] `napari-mri` - "No module named 'napari_mri'" (weird packing error?)
- [ ] `skeleton-finder`: broken package, no python files
- [ ] `napari-yolov5` - No module named 'magicgui.events' in `__init__`
- [x] `nfinder` - lists no dependencies (fix submitted https://github.com/santi-rodriguez/nfinder/pull/1)
- [x] `beetlesafari` - "No module named 'napari_pyclesperanto_assistant'" (notified in https://github.com/haesleinhuepf/beetlesafari/issues/2)

## Package missing manifest in sdist/wheel

- [x] `btrack` (fix submitted in https://github.com/quantumjot/BayesianTracker/pull/153)
- [x] `napari-stl-exporter` (latest release on pypi is missing a lot of stuff, but a lot of changes were made on 6/21/22 which should fix the next release)

## Might need conda

- [x] `napari-pyclesperanto-assistant` - (actually this one seems to be working for me now... curious if it works on aws)
- [ ] `grabber-ift` - failed to install
- [ ] `napari-lazy-openslide` - OSError: libopenslide.so.0: cannot open shared object file
- [ ] `napari-cupy-image-processing` - no install
- [ ] `napari-sdeconv` - maybe failed to build?
- [ ] `napari-yapic-prediction` - 'No module named 'tensorflow' (upstream dependency requires tensorflow, but none of the packages list as a requirement.  not sure what the background story is there, might not be fixed).

### Nothing we can do

- [x] `napari-tomoslice`: pins napari to 0.4.12 , which doesn't work with npe2 (https://github.com/alisterburt/napari-tomoslice/issues/7)
- [x] `napari-subboxer`: pins napari to 0.4.12, which doesn't work with npe2  (https://github.com/alisterburt/napari-tomoslice/issues/7)

**Comment by chili-chiu** [comment]
@tlambert03 I just updated napari-labels-overlap, let me know if there's still an error, thanks!

**Comment by tlambert03** [comment]
perfect!   thanks!

```
╰─❯ npe2 fetch napari-labels-overlap
name: napari-labels-overlap
display_name: napari labels overlap
schema_version: 0.1.0
contributions:
  commands:
  - id: napari-labels-overlap.labels_overlap
    title: labels_overlap
    python_name: napari_labels_overlap._dock_widget:labels_overlap
  widgets:
  - command: napari-labels-overlap.labels_overlap
    display_name: labels overlap
    autogenerate: true
```

**Comment by tlambert03** [comment]
see napari/npe2api

**Comment by nclack** [comment]
Hey @tlambert03 could you note why you're closing? 

Also, is there a similar tracking issue in `napari/npe2api`?

**Comment by tlambert03** [comment]
Because they're all working now.  No similar issue over there.  Closing cause there's no more errors
