### ISSUE TITLE
What's left before release?

### ISSUE THREAD

**Issue by tlambert03** [napari/npe2#32]
please add bullet points here for things that need to be done before napari depends on npe2 and it is "active"

- [x] publish on pypi, and it will also need to be on conda-forge for the napari package
- [x] docs done. See napari/napari#3818
   - [x] intro guide drafted
   - [x] manifest spec drafted
   - [x] migration guide drafted
- [x] do final audit of all fields in the schema, making sure they are A) very clearly defined in the field description, and B) provide very clear errors when not correct.  See #48 

- [x] basic napari install dialog support napari/napari#3694 

non critical

- [ ] test the napari integration code better.
- [x] get tests on the npe2 side close to 100% (we're doing ok, but now's a great time to get full coverage) #70 
- [x] Reader call order priority... how to deal with priority across npe1/npe2. See #41.
- [x] napari preferences > plugins panel. user defined sort order
- [x] npe2 conversion cli tool done
- [x] move to napari team space
- [x] update readme
- [x] #47 
- [x] autocomplete support for schema #50 

future
- [x] #36

**Comment by nclack** [comment]
added a couple bullet points to the issue comment.

I listed "user defined search order in the preferences panel" but I'm thinking it's not critical. It might be something that's npe1 only. Is that acceptable?

**Comment by tlambert03** [comment]
yeah, that's great.  not sure yet whether we should support the sorting.  i'm not sure it was terribly useful.  Now that we have extension support, it's even less useful, and perhaps along with https://github.com/napari/napari/pull/3502 we don't need it at all?
